executable("main") {
  sources = [
    "main.cpp",
  ]

  include_dirs = [ "." ]

  if (is_win) {
    cflags = [ 
      "/EHsc",  # 启用 C++ 异常处理
    ]

    defines = [
      "UNICODE",
      "_UNICODE",
    ]

    ldflags = [
      "/SUBSYSTEM:WINDOWS",
      "glfw3.lib",
      "glad.lib",
      "user32.lib",
      "gdi32.lib",
      "shell32.lib",
      "opengl32.lib",
    ]

    if (is_debug) {
      cflags += [
        "/MTd",
        "/Zi",
        "/Od",
        "/Fd",
      ]

      ldflags += [
        "/DEBUG",
      ]
    } else {
      cflags += [
        "/MT",
        "/O2",
      ]

      ldflags += [
        "/OPT:REF",
        "/OPT:ICF",
        "/LTCG",
      ]
    }

    vcpkg_root = getenv("VCPKG_ROOT")
    assert(vcpkg_root != "", "请先设置环境变量 VCPKG_ROOT")

    if (target_cpu == "x86") {
      include_dirs += [ 
        vcpkg_root + "/installed/x86-windows-static/include",
      ]
      ldflags += [ 
        "/MACHINE:X86",
        "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x86",
        "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x86",
        "/LIBPATH:" + vcpkg_root + "/installed/x86-windows-static/lib",
      ]
    } else if (target_cpu == "x64") {
      include_dirs += [ 
        vcpkg_root + "/installed/x64-windows-static/include",
      ]
      ldflags += [ 
        "/MACHINE:X64",
        "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64",
        "/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64",
        "/LIBPATH:" + vcpkg_root + "/installed/x64-windows-static/lib",
      ]
    }
  } else if (is_linux) {
    defines += [ 
      "_GNU_SOURCE",
      "__linux__",
    ]

    ldflags += [
      "-Wl",
    ]
  }
}